GET http://localhost:3000/surveys

###

GET http://localhost:3000/surveys/62a7b588dfd26e7c18503f7c

###

POST http://localhost:3000/surveys
Content-Type: application/json

{
    "name": "Electives",
    "dateCloses": "2023-06-12T23:19:00.000Z",
    "owner": "Jason",
    "published": false,
    "question": {
        "prompt": "What electives",
        "answers": ["CS380", "CS455", "CS460"]
    },
    "responses": [{
        "name": "Jarrel",
        "choice": "CS380"
    },
    {   "name": "Conner",
        "choice": "CS455"}
    ]
}

###

DELETE http://localhost:3000/surveys/62a7cc44e5943024e89b5d45

###

PUT http://localhost:3000/surveys/62a7cc44e5943024e89b5d45/status
Content-Type: application/json

{
    "published": true
}

###

PUT http://localhost:3000/surveys/62a7ce0cf58c5400d567d29d/question
Content-Type: application/json

{
    "question": {
        "prompt": "Where am I?"
    }
}

###

GET http://localhost:3000/surveys/current

###

PUT http://localhost:3000/surveys/62a7ce0cf58c5400d567d29d/user
Content-Type: application/json

{
    "responses": {
        "name": "Colby",
        "choice": "CS460"
    }
}

###

DELETE http://localhost:3000/surveys/62a7ce0cf58c5400d567d29d/Liam/delete

###

GET http://localhost:3000/surveys/62a7ce0cf58c5400d567d29d/responses